name: wdrożenie na serwer FTP
on:
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Wdrożenie aplikacji
      uses: SamKirkland/FTP-Deplou-Action@v4.3.4
      with:
        server: "s1.ct8.pl"
        server-dir: "./public_html/wp-content/themes/asia_grzyska/"
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
